// The 60 species the model was trained on (model/h5/labels.json), duplicated
// here so the client has its own copy to build the life list roster from —
// keep in sync if the model is retrained with a different species set.
const SPECIES_IDS = [
  'Barn_Owl',
  'Barn_Swallow',
  'Black_headed_Gull',
  'Canada_Goose',
  'Carrion_Crow',
  'Coal_Tit',
  'Common_Blackcap',
  'Common_Buzzard',
  'Common_Chiffchaff',
  'Common_Kestrel',
  'Common_Kingfisher',
  'Common_Linnet',
  'Common_Moorhen',
  'Common_Pheasant',
  'Common_Raven',
  'Common_Swift',
  'Dunnock',
  'Eurasian_Blackbird',
  'Eurasian_Blue_Tit',
  'Eurasian_Bullfinch',
  'Eurasian_Chaffinch',
  'Eurasian_Collared_Dove',
  'Eurasian_Coot',
  'Eurasian_Greenfinch',
  'Eurasian_Jackdaw',
  'Eurasian_Jay',
  'Eurasian_Magpie',
  'Eurasian_Nuthatch',
  'Eurasian_Oystercatcher',
  'Eurasian_Skylark',
  'Eurasian_Sparrowhawk',
  'Eurasian_Treecreeper',
  'Eurasian_Wren',
  'European_Goldfinch',
  'European_Herring_Gull',
  'European_Robin',
  'European_Starling',
  'Great_Spotted_Woodpecker',
  'Great_Tit',
  'Green_Woodpecker',
  'Grey_Heron',
  'Grey_Partridge',
  'Grey_Wagtail',
  'House_Martin',
  'House_Sparrow',
  'Long_tailed_Tit',
  'Mallard',
  'Mistle_Thrush',
  'Mute_Swan',
  'Northern_Lapwing',
  'Pied_Wagtail',
  'Red_Kite',
  'Reed_Bunting',
  'Rook',
  'Song_Thrush',
  'Stock_Dove',
  'Tawny_Owl',
  'Willow_Warbler',
  'Woodpigeon',
  'Yellowhammer',
];

// iNaturalist taxon id for each species, resolved once against
// /v1/observations/species_counts (place_id=6857, i.e. the UK) and pinned
// here so the rarity meter can fetch all 60 counts in a single bulk
// request instead of one lookup per species. A few of these differ from
// our label because iNaturalist's preferred common name doesn't match the
// UK/trained-model name for the same species (e.g. Common Pheasant is
// listed there as "Ring-necked Pheasant"; Pied Wagtail, the UK subspecies,
// rolls up under the species-level "White Wagtail").
const TAXON_IDS = {
  Barn_Owl: 20445,
  Barn_Swallow: 11901,
  Black_headed_Gull: 144510,
  Canada_Goose: 7089,
  Carrion_Crow: 204496,
  Coal_Tit: 144823,
  Common_Blackcap: 15282,
  Common_Buzzard: 204472,
  Common_Chiffchaff: 117016,
  Common_Kestrel: 472766,
  Common_Kingfisher: 2599,
  Common_Linnet: 558634,
  Common_Moorhen: 201282,
  Common_Pheasant: 981,
  Common_Raven: 8010,
  Common_Swift: 6638,
  Dunnock: 13988,
  Eurasian_Blackbird: 12716,
  Eurasian_Blue_Tit: 144849,
  Eurasian_Bullfinch: 9462,
  Eurasian_Chaffinch: 10070,
  Eurasian_Collared_Dove: 2969,
  Eurasian_Coot: 482,
  Eurasian_Greenfinch: 145360,
  Eurasian_Jackdaw: 336399,
  Eurasian_Jay: 8088,
  Eurasian_Magpie: 891696,
  Eurasian_Nuthatch: 14824,
  Eurasian_Oystercatcher: 4843,
  Eurasian_Skylark: 7347,
  Eurasian_Sparrowhawk: 5106,
  Eurasian_Treecreeper: 7450,
  Eurasian_Wren: 145363,
  European_Goldfinch: 9398,
  European_Herring_Gull: 204533,
  European_Robin: 13094,
  European_Starling: 14850,
  Great_Spotted_Woodpecker: 17871,
  Great_Tit: 203153,
  Green_Woodpecker: 144243,
  Grey_Heron: 4954,
  Grey_Partridge: 831,
  Grey_Wagtail: 13688,
  House_Martin: 64705,
  House_Sparrow: 13858,
  Long_tailed_Tit: 7278,
  Mallard: 6930,
  Mistle_Thrush: 12735,
  Mute_Swan: 6921,
  Northern_Lapwing: 4857,
  Pied_Wagtail: 13695,
  Red_Kite: 5267,
  Reed_Bunting: 9201,
  Rook: 8029,
  Song_Thrush: 12748,
  Stock_Dove: 3033,
  Tawny_Owl: 19898,
  Willow_Warbler: 117055,
  Woodpigeon: 3048,
  Yellowhammer: 9195,
};

// Matches the formatting ResultCard.js applies to a raw predicted_class.
export function formatSpeciesName(id) {
  if (!id) return '';
  return id.replace(/^\d+\./, '').replace(/_/g, ' ');
}

export const SPECIES = SPECIES_IDS.map((id) => ({
  id,
  name: formatSpeciesName(id),
  taxonId: TAXON_IDS[id],
})).sort((a, b) => a.name.localeCompare(b.name));

export const SPECIES_COUNT = SPECIES.length;
